# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wGUpCTqVPfrFSzxLKEmebIzRZ55rzqt
"""



import numpy as np
import pandas as pd
import pip
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.pipeline import Pipeline

"""The above libraries are commonly used in Colab. `numpy`, `pandas`, and `scikit-learn` are usually pre-installed.

To ensure `xgboost` is available, you can install it using pip if it's not already present:
"""

pip install xgboost

engineered_df = pd.read_csv('/content/drive/MyDrive/spring/engineered_dataset.csv')

features = [
    'Material_Type',
    'Strength_PSI',
    'Weight_Capacity_KG',
    'Biodegradability_%',
    'Recyclability_%'
]

X = engineered_df[features]

# Targets
y_cost = engineered_df['Cost_per_KG_USD']
y_co2 = engineered_df['CO2_Emission_Score_%']

# ----------------------------------------------
# Train-Test Split
# ----------------------------------------------
from sklearn.model_selection import train_test_split

X_train, X_test, y_cost_train, y_cost_test = train_test_split(
    X, y_cost, test_size=0.2, random_state=42
)

_, _, y_co2_train, y_co2_test = train_test_split(
    X, y_co2, test_size=0.2, random_state=42
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Define preprocessing steps for numerical and categorical features
# Identify categorical and numerical features
categorical_features = ['Material_Type']
numerical_features = [
    'Strength_PSI',
    'Weight_Capacity_KG',
    'Biodegradability_%',
    'Recyclability_%'
]

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

rf_cost_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=200,
        max_depth=10,
        random_state=42
    ))
])

rf_cost_pipeline.fit(X_train, y_cost_train)

rf_cost_predictions = rf_cost_pipeline.predict(X_test)

rf_cost_rmse = np.sqrt(mean_squared_error(y_cost_test, rf_cost_predictions))
rf_cost_mae = mean_absolute_error(y_cost_test, rf_cost_predictions)
rf_cost_r2 = r2_score(y_cost_test, rf_cost_predictions)

print("===== RANDOM FOREST (COST) =====")
print("RMSE:", rf_cost_rmse)
print("MAE:", rf_cost_mae)
print("R2 Score:", rf_cost_r2)

xgb_co2_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', XGBRegressor(
        n_estimators=200,
        learning_rate=0.1,
        max_depth=6,
        random_state=42
    ))
])

xgb_co2_pipeline.fit(X_train, y_co2_train)

xgb_co2_predictions = xgb_co2_pipeline.predict(X_test)

xgb_co2_rmse = np.sqrt(mean_squared_error(y_co2_test, xgb_co2_predictions))
xgb_co2_mae = mean_absolute_error(y_co2_test, xgb_co2_predictions)
xgb_co2_r2 = r2_score(y_co2_test, xgb_co2_predictions)

print("\n===== XGBOOST (CO2) =====")
print("RMSE:", xgb_co2_rmse)
print("MAE:", xgb_co2_mae)
print("R2 Score:", xgb_co2_r2)

# ----------------------------------------------
# AI RECOMMENDATION SYSTEM
# ----------------------------------------------

# Predict cost and CO2 for entire dataset
engineered_df['Predicted_Cost'] = rf_cost_pipeline.predict(X)
engineered_df['Predicted_CO2'] = xgb_co2_pipeline.predict(X)

# Normalize predictions (Lower is better)
engineered_df['Cost_Score'] = 1 - (
    (engineered_df['Predicted_Cost'] - engineered_df['Predicted_Cost'].min()) /
    (engineered_df['Predicted_Cost'].max() - engineered_df['Predicted_Cost'].min())
)

engineered_df['CO2_Score'] = 1 - (
    (engineered_df['Predicted_CO2'] - engineered_df['Predicted_CO2'].min()) /
    (engineered_df['Predicted_CO2'].max() - engineered_df['Predicted_CO2'].min())
)

# Final AI Recommendation Score (Equal Weight)
engineered_df['AI_Recommendation_Score'] = (
    engineered_df['Cost_Score'] * 0.5 +
    engineered_df['CO2_Score'] * 0.5
)

# Rank materials
ranked_materials = engineered_df.sort_values(
    by='AI_Recommendation_Score',
    ascending=False
)

print("\n===== TOP 10 RECOMMENDED MATERIALS =====")
print(ranked_materials[['Material_Type',
                        'Predicted_Cost',
                        'Predicted_CO2',
                        'AI_Recommendation_Score']].head(10))

# Save ranked output
ranked_materials.to_csv("AI_Material_Ranking.csv", index=False)

import joblib

# Define filenames for your models
rf_cost_model_filename = 'rf_cost_pipeline.joblib'
xgb_co2_model_filename = 'xgb_co2_pipeline.joblib'

# Save the Random Forest pipeline for cost prediction
joblib.dump(rf_cost_pipeline, rf_cost_model_filename)
print(f"Random Forest Cost Model saved to {rf_cost_model_filename}")

# Save the XGBoost pipeline for CO2 prediction
joblib.dump(xgb_co2_pipeline, xgb_co2_model_filename)
print(f"XGBoost CO2 Model saved to {xgb_co2_model_filename}")

"""You can then load a saved model at a later time like this:"""

import joblib

# Load the saved Random Forest pipeline
loaded_rf_cost_pipeline = joblib.load('rf_cost_pipeline.joblib')
print("Random Forest Cost Model loaded successfully!")

# You can now use 'loaded_rf_cost_pipeline' to make new predictions
# For example:
# new_predictions = loaded_rf_cost_pipeline.predict(new_data)

# =========================================
# TEST NEW MATERIAL SAMPLE
# =========================================

import pandas as pd

# Create a sample material (change values to test different cases)
test_sample = pd.DataFrame({
    'Material_Type': ['Kraft Paper'],
    'Strength_PSI': [6000],
    'Weight_Capacity_KG': [10],
    'Biodegradability_%': [90],
    'Recyclability_%': [85]
})

# Predict Cost
predicted_cost = rf_cost_pipeline.predict(test_sample)[0]

# Predict CO2
predicted_co2 = xgb_co2_pipeline.predict(test_sample)[0]

# Normalize using training dataset range
cost_min = engineered_df['Predicted_Cost'].min()
cost_max = engineered_df['Predicted_Cost'].max()

co2_min = engineered_df['Predicted_CO2'].min()
co2_max = engineered_df['Predicted_CO2'].max()

cost_score = 1 - ((predicted_cost - cost_min) / (cost_max - cost_min))
co2_score = 1 - ((predicted_co2 - co2_min) / (co2_max - co2_min))

ai_score = 0.5 * cost_score + 0.5 * co2_score

print("===== TEST RESULT =====")
print("Predicted Cost:", round(predicted_cost, 3))
print("Predicted CO2:", round(predicted_co2, 3))
print("AI Recommendation Score:", round(ai_score, 3))